BoardConfigVendor: fix building of libcameraservice
USE_CAMERA_STUB needs to be false because we're using proprietary
froyo camera libs.  Without it the build errors on:

	prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: out/target/product/u8150/obj/SHARED_LIBRARIES/libcameraservice_intermediates/CameraService.o: in function HAL_openCameraHardware:frameworks/base/services/camera/libcameraservice/CameraService.cpp:1754: error: undefined reference to 'openCameraHardware'
	collect2: ld returned 1 exit status
	make: *** [out/target/product/u8150/obj/SHARED_LIBRARIES/libcameraservice_intermediates/LINKED/libcameraservice.so] Error 1

Fixed in the device tree as well, see: http://review.cyanogenmod.com/#change,9588